nameOverride: null

enabled: true

metrics:
  platformEnabled: false
  userWorkloadsEnabled: false

logging:
  enabled: false

tracing:
  enabled: false

analytics:
  incidentDetection:
    enabled: false
  rightSizing:
    namespaceEnabled: false
    namespaceBinding: ""
    virtualizationEnabled: false
    virtualizationBinding: ""
